gfc/gfc/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, re_path, URLPattern
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from financial_companion import views

urlpatterns: list[URLPattern] = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),
    path('sign_up/', views.sign_up_view, name='sign_up'),
    path('log_in/', views.log_in_view, name='log_in'),
    path('log_out/', views.log_out_view, name='log_out'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path(
        'categories/<str:search_name>/',
        views.category_list_view,
        name='categories_list'),
    path(
        'categories/',
        views.category_list_view,
        name='categories_list_redirect'),
    path(
        'groups/<str:search_name>/',
        views.all_groups_view,
        name='all_groups'),
    path(
        'groups/',
        views.all_groups_view,
        name='all_groups_redirect'),
    path(
        'add_monetary_account/',
        views.add_monetary_account_view,
        name="add_monetary_account"),
    path(
        'view_accounts/',
        views.view_user_accounts,
        name='view_accounts'),
    path(
        'create_category/',
        views.create_category_view,
        name="create_category"),
    path(
        'add_transaction/',
        views.add_transaction_view,
        name='add_transaction'),
    path(
        'edit_transaction/<int:pk>',
        views.edit_transaction_view,
        name='edit_transaction'),
    path(
        'delete_transaction/<int:pk>',
        views.delete_transaction_view,
        name='delete_transaction'),
    path(
        'view_transactions/<str:filter_type>',
        views.view_users_transactions,
        name="view_transactions"),
    path(
        'edit_user_details/',
        views.edit_user_details_view,
        name="edit_user_details"),
    path('profile/', views.profile_view, name="profile"),
    path('delete_profile/', views.delete_profile_view, name="delete_profile"),
    path(
        'view_transactions/',
        views.view_users_transactions,
        name="view_transactions_redirect"),
    path(
        'change_password/',
        views.change_password_view,
        name="change_password"),
    path(
        'create_target/category/<int:pk>',
        views.create_category_target_view,
        name="create_category_target"),
    path(
        'create_target/user/',
        views.create_user_target_view,
        name="create_user_target"),
    path(
        'create_target/account/<int:pk>',
        views.create_account_target_view,
        name="create_account_target"),
    path(
        'edit_target/category/<int:pk>',
        views.edit_category_target_view,
        name="edit_category_target"),
    path(
        'edit_target/account/<int:pk>',
        views.edit_account_target_view,
        name="edit_account_target"),
    path(
        'edit_target/user/<int:pk>',
        views.edit_user_target_view,
        name="edit_user_target"),
    path(
        'delete_target/category/<int:pk>',
        views.delete_category_target_view,
        name="delete_category_target"),
    path(
        'delete_target/account/<int:pk>',
        views.delete_account_target_view,
        name="delete_account_target"),
    path(
        'delete_target/user/<int:pk>',
        views.delete_user_target_view,
        name="delete_user_target"),
    path(
        'edit_category/<int:pk>',
        views.edit_category_view,
        name="edit_category"),
    path(
        'delete_category/<int:pk>',
        views.delete_category_view,
        name="delete_category"),
    path(
        'create_user_group/',
        views.create_user_group_view,
        name="create_user_group"),
    path(
        'delete_user_group/<int:pk>',
        views.delete_user_group_view,
        name="delete_user_group"),
    path(
        'edit_user_group/<int:pk>',
        views.edit_user_group_view,
        name='edit_user_group'),
    path(
        'join_user_group/',
        views.join_user_group_view,
        name="join_user_group"),
    path(
        'remove_user_from_user_group/<int:group_pk>/<int:user_pk>',
        views.remove_user_from_user_group_view,
        name="remove_user_from_user_group"),
    path(
        'make_owner_of_user_group/<int:group_pk>/<int:user_pk>',
        views.make_owner_of_user_group_view,
        name="make_owner_of_user_group"),
    path(
        'add_user_to_user_group/<int:group_pk>',
        views.add_user_to_user_group_view,
        name="add_user_to_user_group"),
    path(
        'reset_password',
        PasswordResetView.as_view(
            template_name="pages/email/password_reset.html"),
        name='password_reset'),
    path(
        'reset_password/done',
        PasswordResetDoneView.as_view(
            template_name="pages/email/password_reset_done.html"),
        name='password_reset_done'),
    path(
        'reset_password/confirm/<uidb64>[0-9A-Za-z]+)-<token>/',
        PasswordResetConfirmView.as_view(
            template_name="pages/email/password_reset_confirm.html"),
        name='password_reset_confirm'),
    path(
        'reset_password/complete/',
        PasswordResetCompleteView.as_view(
            template_name="pages/email/password_reset_complete.html"),
        name='password_reset_complete'),
    path(
        'view_savings_accounts/',
        views.view_savings_accounts,
        name='view_savings_accounts'),
    re_path(
        'individual_account/(?P<pk>\\d+)/(?P<filter_type>\\w+)/$',
        views.individual_account_view,
        name="individual_account"
    ),
    re_path(
        'filter_transaction_request/(?P<redirect_name>\\w+)/$',
        views.filter_transaction_request,
        name="filter_transaction_request"
    ),
    re_path(
        'filter_transaction_request_with_pk/(?P<redirect_name>\\w+)/(?P<pk>\\d+)/$',
        views.filter_transaction_request_with_pk,
        name="filter_transaction_request_with_pk"
    ),
    re_path(
        'individual_account/(?P<pk>\\d+)/$',
        views.individual_account_view,
        name="individual_account_redirect"
    ),
    re_path(
        'edit_monetary_account/(?P<pk>\\d+)/$',
        views.edit_monetary_account_view,
        name="edit_monetary_account"
    ),
    re_path(
        'delete_monetary_account/(?P<pk>\\d+)/$',
        views.delete_monetary_account_view,
        name="delete_monetary_account"
    ),
    re_path(
        'individual_category/(?P<pk>\\d+)/(?P<filter_type>\\w+)/$',
        views.individual_category_view,
        name="individual_category"
    ),
    re_path(
        'individual_category/(?P<pk>\\d+)/$',
        views.individual_category_view,
        name="individual_category_redirect"
    ),
    re_path(
        'individual_transaction/(?P<pk>\\d+)/$',
        views.individual_transaction_view,
        name="individual_transaction"
    ),
    path('quiz/', views.quiz_view, name='quiz'),
    re_path(
        'quiz/(?P<question_total>\\d+)/(?P<sort_type>\\w+)/$',
        views.quiz_view,
        name="quiz_with_params"
    ),
    re_path(
        'quiz_ready/(?P<question_total>\\d+)/$',
        views.quiz_ready_view,
        name="quiz_ready"
    ),
    re_path(
        'quiz_questions/(?P<pk>\\d+)/$',
        views.quiz_question_view,
        name="quiz_questions"
    ),
    re_path(
        'quiz_score/(?P<pk>\\d+)/$',
        views.quiz_score_view,
        name="quiz_score"
    ),
    re_path(
        'individual_group/(?P<pk>\\d+)/$',
        views.individual_group_view,
        name="individual_group_redirect"
    ),
    re_path(
        'individual_group/(?P<pk>\\d+)/(?P<leaderboard>\\w+)/$',
        views.individual_group_view,
        name="individual_group"
    ),
    path('add_transactions_via_bank_statement/',
         views.add_transactions_via_bank_statement,
         name='add_transactions_via_bank_statement'),
    re_path(r'^view_targets(?:/(?P<time>[a-zA-Z]+))?(?:/(?P<income_or_expense>[a-zA-Z]+))?(?:/(?P<target_type>[a-zA-Z]+))?/$',
            views.view_targets,
            name='view_targets'),
    re_path(
        r'^spending_summary(?:/(?P<time>[a-zA-Z]+))?(?:/(?P<currency>[a-zA-Z]+))?/$',
        views.spending_summary,
        name='spending_summary'),
    path('view_recurring_transactions/',
         views.view_users_recurring_transactions,
         name='view_recurring_transactions'),
    path('add_recurring_transaction/',
         views.add_recurring_transaction_view,
         name='add_recurring_transaction'),
    path(
        'edit_recurring_transaction/<int:pk>',
        views.edit_recurring_transaction_view,
        name='edit_recurring_transaction'),
    path(
        'delete_recurring_transaction/<int:pk>',
        views.delete_recurring_transaction_view,
        name='delete_recurring_transaction'),
    re_path(
        'individual_recurring_transaction/(?P<pk>\\d+)/$',
        views.individual_recurring_transaction_view,
        name='individual_recurring_transaction')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gfc/financial_companion/models/abstract_accounts_model.py
from django.db.models import (
    Model,
    CharField
)



class AbstractAccount(Model):
    #Abstract model for all accounts

    name: CharField = CharField(
        max_length = 50,
        blank = False
    )

    description: CharField = CharField(
        max_length = 500,
        blank = True
    )

    class Meta:
        abstract = True

gfc/financial_companion/models/transactions_models.py
from django.db.models import (
    Model,
    CharField,
    DecimalField,
    ImageField,
    DateTimeField,
    ForeignKey,
)
from .accounts_model import Account
from datetime import datetime
from ..helpers.enums import CurrencyType

def change_filename(instance, filename):
    existing_filename = filename.split('.')[-1]
    #get filename
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, existing_filename)
    else:
        # set a random filename
        filename_strings_to_add = [random.choice(string.ascii_letters), str(datetime.now())]
        filename = '{}.{}'.format(''.join(filename_strings_to_add),existing_filename)

    return os.path.join('transactions', filename)

class AbstractTransaction(Model):
    """Abstract model for recording a transaction"""

    title: CharField = CharField(
        blank = False,
        max_length = 30
    )

    description: CharField = CharField(
        blank = True,
        max_length = 200
    )

    image: ImageField = ImageField(
        blank = True,
        height_field = None,
        width_field = None,
        max_length = 100,
        upload_to='change_filename'
    )

    #category = models.ForeignKey(### Category ###)

    #time_of_transaction: DateTimeField = DateTimeField(
    #    blank = False,
    #    default = datetime.now()
    #)

    amount: DecimalField = DecimalField(
        blank = False,
        decimal_places=2,
        max_digits = None,
    )

    currency: CharField = CharField(
        blank = False,
        choices = CurrencyType.choices,
        max_length = 3
    )

    sender_account = models.ForeignKey(Account, related_name = "sender_account")
    reciever_account = models.ForeignKey(Account, related_name = "reciever_account")

    class Meta:
        abstract = True

gfc/financial_companion/forms/add_recurring_transaction_form.py
from datetime import date
from django import forms
from financial_companion.models import PotAccount, RecurringTransaction, User, Category, Account
from django.forms.widgets import DateInput
from django.db.models import QuerySet


class AddRecurringTransactionForm(forms.ModelForm):
    """Form to add a new recurring transaction"""

    def __init__(self, user, *args, **kwargs):
        super(AddRecurringTransactionForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset: QuerySet[Account] = Category.objects.filter(
            user=user.id)
        self.fields['sender_account'].queryset: QuerySet[Account] = Account.objects.filter(
            user=user.id)
        self.fields['receiver_account'].queryset: QuerySet[Account] = Account.objects.filter(
            user=user.id)
        self.fields['category'].label_from_instance: str = self.label_from_instance
        self.fields['sender_account'].label_from_instance: str = self.label_from_instance
        self.fields['receiver_account'].label_from_instance: str = self.label_from_instance
        self.user: User = user

    def label_from_instance(self, obj) -> str:
        """Return objects name"""
        return obj.name

    class Meta:
        model: RecurringTransaction = RecurringTransaction
        fields: list[str] = [
            'title',
            'description',
            'file',
            'category',
            'amount',
            'currency',
            'sender_account',
            'receiver_account',
            'interval',
            'start_date',
            'end_date']
        widgets: dict[str, DateInput] = {
            'start_date': DateInput(attrs={'type': 'date', 'placeholder': 'yyyy-mm-dd', 'class': 'form-control'}),
            'end_date': DateInput(attrs={'type': 'date', 'placeholder': 'yyyy-mm-dd', 'class': 'form-control'}),
        }

    def save(self, instance: RecurringTransaction = None) -> RecurringTransaction:
        """Create a new transaction."""
        super().save(commit=False)
        if instance is None:
            recurring_transaction: RecurringTransaction = RecurringTransaction.objects.create(
                title=self.cleaned_data.get('title'),
                description=self.cleaned_data.get('description'),
                file=self.cleaned_data.get('file'),
                category=self.cleaned_data.get('category'),
                amount=self.cleaned_data.get('amount'),
                currency=self.cleaned_data.get('currency'),
                sender_account=self.cleaned_data.get('sender_account'),
                receiver_account=self.cleaned_data.get('receiver_account'),
                interval=self.cleaned_data.get('interval'),
                start_date=self.cleaned_data.get('start_date'),
                end_date=self.cleaned_data.get('end_date')
            )
        else:
            recurring_transaction: RecurringTransaction = super().save(commit=True)
        return recurring_transaction

    def clean(self):
        """Clean the data and generate messages for any errors."""

        super().clean()
        sender_account: Account = self.cleaned_data.get('sender_account')
        receiver_account: Account = self.cleaned_data.get('receiver_account')
        start_date: date = self.cleaned_data.get('start_date')
        end_date: date = self.cleaned_data.get('end_date')
        users_accounts: QuerySet[PotAccount] = PotAccount.objects.filter(
            user=self.user)
        ids: list[Account] = []
        for account in users_accounts:
            ids.append(account.id)
        if sender_account == receiver_account:
            self.add_error(
                'receiver_account',
                'The sender and receiver accounts cannot be the same.')
        elif not ((sender_account.id in ids) or (receiver_account.id in ids)):
            self.add_error(
                'sender_account',
                'Neither the sender or reciever are accounts with a balance to track.')
            self.add_error(
                'receiver_account',
                'Neither the sender or reciever are accounts with a balance to track.')
        if start_date > end_date:
            self.add_error(
                'end_date',
                'End date cannot precede start date.')

gfc/financial_companion/forms/add_user_to_user_group_form.py
from django import forms


class AddUserToUserGroupForm(forms.Form):
    """Form enabling users to be added to user groups."""

    user_email: forms.EmailField = forms.EmailField(
        label="",
        widget=forms.TextInput(
            attrs={
                'placeholder': "Enter User's Email",
                'class': 'form-control rounded'}))

gfc/financial_companion/forms/create_category_form.py
from django import forms
from financial_companion.models import Category
from typing import Any


class CategoryForm(forms.ModelForm):
    """Form to add a new transaction"""

    class Meta:
        model: Category = Category
        fields: list[str] = ['name', 'description']
        widgets: dict[str, Any] = {'description': forms.Textarea()}

    def save(self, current_user, instance: Category = None) -> Category:
        """Create a new category."""
        super().save(commit=False)
        if instance is None:
            category: Category = Category.objects.create(
                user=current_user,
                name=self.cleaned_data.get('name'),
                description=self.cleaned_data.get('description')
            )
        else:
            category: Category = instance
            category.name: str = self.cleaned_data.get('name')
            category.description: str = self.cleaned_data.get('description')
            category.save()

        return category

gfc/financial_companion/forms/join_user_group_form.py
from django import forms


class JoinUserGroupForm(forms.Form):
    """Form enabling logged in users to join user groups."""

    invite_code: forms.CharField = forms.CharField(
        label="",
        max_length=8,
        min_length=8,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter Group Invite Code',
                'class': 'form-control rounded'}))

gfc/financial_companion/templates/pages/add_recurring_transaction.html
{% extends "page.html" %}
{% load static %}

<!-- Title -->
{% block title %}Recurring Transaction Form{% endblock %}

<!-- Content -->
{% block content %}
  <head>
    <script src="{% static 'javascript/autocomplete.js' %}"></script>
    <script
      src="https://code.jquery.com/jquery-3.6.3.min.js"
      integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
      crossorigin="anonymous"></script>
      <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
      <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
      <script>
        autocomplete('#id_sender_account');
        autocomplete('#id_receiver_account');
    </script>
  </head>

    <h1>Recurring Transaction</h1>

    {% if edit %}
      <form action='{% url 'edit_recurring_transaction' pk %}' method="post" enctype='multipart/form-data'>
    {% else %}
      <form action='{% url 'add_recurring_transaction'%}' method="post" enctype='multipart/form-data'>
    {% endif %}
      {% csrf_token %}

      {% include 'partials/form.html' with form=form %}
      <button type="submit" name="submit_type" value="Submit" class="btn btn-primary">
    {% if edit %}
        Edit Recurring Transaction
        {% else %}
            Create Recurring Transaction
        {% endif %}
    </form>
{% endblock %}

gfc/financial_companion/templates/pages/add_transaction.html
{% extends "page.html" %}
{% load static %}

<!-- Title -->
{% block title %}Transaction Form{% endblock %}

<!-- Content -->
{% block content %}
    <head>
      <script src="{% static 'javascript/autocomplete.js' %}"></script>
      <script
        src="https://code.jquery.com/jquery-3.6.3.min.js"
        integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
        crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <script>
          autocomplete('#id_sender_account');
          autocomplete('#id_receiver_account');
      </script>
    </head>
    
    <h1>Transaction Form</h1>

    {% if edit %}
      <form action='{% url 'edit_transaction' pk %}' method="post" enctype='multipart/form-data'>
    {% else %}
      <form action='{% url 'add_transaction'%}' method="post" enctype='multipart/form-data'>
    {% endif %}
      {% csrf_token %}

    <div class="row mb-4 gx-2">
      <div class="col-md-auto">
        <a class="btn btn-primary" href="{% url 'create_category' %}">Add New Category</a>
      </div>
      <div class="col-md-auto">
        <a class="btn btn-primary" href="{% url 'add_monetary_account' %}">Add New Account</a>
      </div>
      <div class="col-md-auto">
        <a class="btn btn-primary" href="{% url 'add_transactions_via_bank_statement' %}">Upload Bank Statement</a>
      </div>
    </div>

      {% include 'partials/form.html' with form=form %}
      <button type="submit" name="submit_type" value="Submit Transaction" class="btn btn-primary">
    {% if edit %}
        Edit Transaction
        {% else %}
            Create Transaction
        {% endif %}
{% endblock %}

gfc/financial_companion/templates/pages/all_groups.html
{% extends "page.html" %}

<!-- Title -->
{% block title %}View Groups{% endblock %}

<!-- Content -->
{% block content %}
  <div>

    <div align="center" class="w-75 container-fluid">
      <h1>Groups</h1>
      <h6>This is where you are able to create groups. Here you can create and manage these Groups.
      You are able to compete against other members of the group in order to find who is the best
      at sticking to their targets. Good luck and have fun!!</h6>
    </div>

    <div align="center" class="w-50 container-fluid">
      <a class="btn btn-primary" href="{% url 'create_user_group'%}">Add New</a>
      <a class="btn btn-primary" href="{% url 'all_groups' search_name='all'%}">View All</a>
      <br/><br>
      <form action='{% url 'join_user_group' %}' method="post" class="input-group  d-flex justify-content-center">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Join" class="btn btn-primary">
      </form>
      <br>
      {% include 'partials/search_bar.html' %}
    </div>

    <br>

    {%if groups%}
      <div class="row">
        {% include 'partials/groups/group_card.html' %}
      </div>
    {% else %}
      <h2 class="text-center">You have no groups yet</h2>
    {% endif %}

  </div>
{% endblock %}

gfc/financial_companion/templates/pages/category_list.html
{% extends "page.html" %}

<!-- Title -->
{% block title %}View Categories{% endblock %}

<!-- Content -->
{% block content %}
  <div>
    <div align="center" class="w-50 container-fluid">
      <h1>Categories</h1>
      <a class="btn btn-primary" href="{% url 'create_category' %}">Add New</a> <a class="btn btn-primary" href="{% url 'categories_list' search_name='all'%}">View All</a>
      <br/><br>
      {% include 'partials/search_bar.html' %}
    </div>
    <br>
    {%if categories%}
    <div class="row">
          {%for category in categories %}
            <div class="col-sm-4 py-4">
              <div class="card justify-content-center text-center h-100">
                  <div class="card-header pb-1">
                      <h4 class="card-title">{{ category.name }}</h5>
                  </div>
                  <div class="card-body">
                      <p class="card-text">{{ category.description }}</p>
                  </div>
                  <div class="card-footer">
                      <a href="{% url 'individual_category' pk=category.id filter_type='all' %}" class="btn btn-outline-primary">View</a>
                      <a href="{% url 'delete_category' pk=category.id %}" class="btn btn-outline-danger" onclick="return confirm('Are you sure you want to delete this category?')">Delete</a>
                  </div>
              </div>
            </div>
          {% endfor %}
      </div>
      {% else %}
              <h2 class="text-center"> You have no categories yet</h2>
      {% endif %}
  </div>
{% endblock %}

gfc/financial_companion/templates/pages/edit_user_details.html
{% extends "page.html" %}

<!-- Title -->
{% block title %}Edit Details{% endblock %}

<!-- Content -->
{% block content %}
    <h1>User Edit Details</h1>
    <form action='{% url 'edit_user_details' %}' method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {% include 'partials/form.html' with form=form %}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

gfc/financial_companion/templates/pages/individual_category.html
{% extends "partials/view_models/view_model.html" %}

{% block object_name %}{{category.name}}{% endblock %}
{% block model_name %}Category{% endblock %}

{% block page_header_model %}Category{% endblock %}
{% block page_header_name %}{{category.name}}{% endblock %}

{% block card_title %}Category Information:{% endblock %}

{% block edit_delete_buttons %}
    {% url 'create_category_target' pk=category.id as add_target %}
    {% url 'edit_category' pk=category.id as edit_category %}
    {% url 'delete_category' pk=category.id as delete_category %}
    {% include "partials/view_models/edit_and_delete_models_buttons.html" with add_target_URL=add_target edit_URL=edit_category delete_URL=delete_category model_name="category"%}
{% endblock %}

{% block confirmation_model_name %}category{% endblock %}

{% block table_content %}
    {% if category.description %}
        <li class="list-group-item"><strong>Description: </strong> {{category.description}}</li>
    {% endif %}
{% endblock %}

{% block additional_items %}
    {% include 'partials/target.html' with targets=category_targets edit_url='edit_category_target' delete_url='delete_category_target' %}
{% endblock %}

{% block view_model_objects_URL %}{% url 'categories_list_redirect' %}{% endblock %}
{% block view_model_objects_text %}View All Categories{% endblock %}

{% block further_content %}
    {% include 'partials/transaction_table.html' with transactions=transactions redirect_name="individual_category" pk=category.id %}
{% endblock %}

gfc/financial_companion/templates/pages/individual_group.html
{% extends "partials/view_models/view_model.html" %}

{% block object_name %}{{group.name}}{% endblock %}
{% block model_name %}Group{% endblock %}

{% block page_header_model %}Group{% endblock %}
{% block page_header_name %}{{group.name}}{% endblock %}

{% block card_title %}Group Information:{% endblock %}

{% block edit_delete_buttons %}
  {% if is_owner %}
    {% url 'edit_user_group' pk=group.id as edit_group %}
    {% url 'delete_user_group' pk=group.id as delete_group %}
    {% include "partials/view_models/edit_and_delete_models_buttons.html" with edit_URL=edit_group delete_URL=delete_group model_name="group"%}
  {% endif %}
{% endblock %}

{% block confirmation_model_name %}transaction{% endblock %}

{% block table_content %}
  <li class="list-group-item"><strong>Join code: </strong> {{group.invite_code}}</li>
  <li class="list-group-item"><strong>Description: </strong> {{group.description}}</li>
  <li class="list-group-item"><strong>Number of members: </strong> {{count}}</li>
{% endblock %}

{% block table_footer %}
  If you have any questions regarding the group please contact the owner at: <strong>{{group.owner_email}}</strong>
{% endblock %}

{% block additional_items %}
  {% include "partials/view_models/model_photo.html" with picture=group.group_picture name=group.name%}
{% endblock %}

{% block view_model_objects_URL %}{% url 'all_groups_redirect' %}{% endblock %}
{% block view_model_objects_text %}View All Groups{% endblock %}

{% block further_content %}
  <div class="text-center mb-3">
    <a href="{% url 'individual_group' pk=group.id leaderboard=True %}" class="btn btn-primary mx-2">View Leaderboard</a>
    <a href="{% url 'individual_group_redirect' pk=group.id %}" class="btn btn-primary mx-2">View Members</a>
  </div>
  <div class="row">
    <div class="container">
      <div class="row">
        <div class="card">
          <div class="card-body">
            {% if leaderboard %}
              <div class="col-12">
                <div class="row">
                  <div class="col-12 col-md-8 mt-1">
                    <div class="card-title">
                      <h4>Leaderboard:</h4>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="card-text">
                    <p>
                      This leaderboard ranks you based on the number of targets that you have completed.
                      Looking forward to see who will be taking the number one spot! Good luck to you all.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            {% include 'partials/groups/completed_leaderboard.html' with members=members completed=completed %}
          {% else %}
            {% if is_owner %}
              <div class="col-12">
                <div class="row">
                  <div class="col-12 col-md-8 mt-1">
                    <div class="card-title">
                      <h4>Members:</h4>
                    </div>
                  </div>
                  <div class="col-12 col-md-4 mb-3 d-flex justify-content-start justify-content-md-end">
                    <form action='{% url 'add_user_to_user_group' group_pk=group.id %}' method="post" class="input-group  d-flex justify-content-center">
                      {% csrf_token %}
                      {{ add_user_form }}
                      <input type="submit" value="Add Member" class="btn btn-primary">
                    </form>
                  </div>
                </div>
              </div>
              {% include 'partials/groups/owners_members_table.html' with members=members owners_email=owners_email %}
            {% else %}
              <div class="col-12 col-md-8">
                <div class="card-title">
                  <h4>Members:</h4>
                </div>
              </div>
              {% include 'partials/groups/users_members_table.html' with members=members %}
            {% endif %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

gfc/financial_companion/templates/pages/monetary_accounts_form.html
{% extends "page.html" %}

<!-- Title -->
{% block title %}Monetary Accounts Form{% endblock %}

<!-- Content -->
{% block content %}
    <h1>Monetary Accounts Form</h1>

    {% if form_toggle %}
    <form method="POST" class="row gy-2">
        {% csrf_token %}
        <h3 class="col-md-auto">Account Type</h3>
        {% for monetary_account_type in monetary_account_types %}
            <div class="col-lg-2">
            {% if account_type == monetary_account_type %}
                <button type="submit" name="account_type" value="{{monetary_account_type}}" class="btn btn-primary col-12">{{monetary_account_type.capitalize}}</button>
            {% else %}
                <button type="submit" name="account_type" value="{{monetary_account_type}}" class="btn btn-outline-secondary col-12">{{monetary_account_type.capitalize}}</button>
            {% endif %}
            </div>
        {% endfor %}
    </form>
    {% else %}
    <h3>{{ account_type.title }}</h3>
    {% endif %}

    <br>
    
    <form method="post">
        {% csrf_token %}
        {% include 'partials/form.html' with form=form %}
      <button type="submit" name="submit_type" value="{{account_type}}" class="btn btn-primary">
        {% if form_toggle %}
            Create Account
        {% else %}
            Edit Account
        {% endif %}
    </button>
    </form>
{% endblock %}